es6-template-literals - Aaron Soukaphay
aaronsoukaphay/c0723-code-solutions pull request #70
Opened 2023-08-07 17:48 UTC by aaronsoukaphay

![Screenshot 2023-08-07 at 10 48 35 AM](https://github.com/aaronsoukaphay/c0723-code-solutions/assets/132744086/60537184-036f-430c-b17f-f49f0b6b3b98)

2023-08-07 17:52 UTC, shawnkost requested changes
Some changes here Aaron! You are not supposed to be creating new variables, you have all the variables you need. You should be changing them to use template literals rather than string concatenation

2023-08-07 17:52 UTC, shawnkost commented on es6-template-literals/index.html
> +      const address = number + ' ' + street;
This should be a template literal

2023-08-07 17:52 UTC, shawnkost commented on es6-template-literals/index.html
> +      const templateAddress = `LearningFuze: ${number} ${street}`;
Delete this

2023-08-07 17:52 UTC, shawnkost commented on es6-template-literals/index.html
> +      console.log(templateAddress);
Delete this

2023-08-07 17:52 UTC, shawnkost commented on es6-template-literals/index.html
> +        ' years old.';
This should be a template literal

2023-08-07 17:52 UTC, shawnkost commented on es6-template-literals/index.html
> +      const templateBio = `Bio: My name is ${firstName} ${lastName} and I am ${age} years old.`;
Delete this

2023-08-07 17:52 UTC, shawnkost commented on es6-template-literals/index.html
> +      console.log(templateBio);
Delete this

2023-08-07 17:52 UTC, shawnkost commented on es6-template-literals/index.html
> +      const applePen = fruit + item;
This should be a template literal

2023-08-07 17:52 UTC, shawnkost commented on es6-template-literals/index.html
> +      const templateApplePen = `${fruit + item}`;
Delete this

2023-08-07 17:52 UTC, shawnkost commented on es6-template-literals/index.html
> +      console.log(templateApplePen);
Delete this

2023-08-07 18:03 UTC, aaronsoukaphay commented
![Screenshot 2023-08-07 at 11 02 02 AM](https://github.com/aaronsoukaphay/c0723-code-solutions/assets/132744086/6a3d08d4-45c3-4249-88f7-7af4a56e0847)

2023-08-08 17:10 UTC, shawnkost requested changes
One change here Aaron!

2023-08-08 17:10 UTC, shawnkost commented on es6-template-literals/index.html
> +      const applePen = `${fruit + item}`;
No `+` needed. That's still doing string concatenation.

2023-08-08 17:14 UTC, shawnkost approved these changes
👍🏻

2023-08-08 20:03 UTC, merged